### ISSUE TITLE
Frequent log entries in container

### ISSUE THREAD

**Issue by gtothill** [vsc55/docker-PyWebScrapBook#3]
Firstly thanks for this docker container of the PyWebScrapBook back end server. I've spent so many years doing research and trying to faithfully store web pages - no other solution has come anywhere close to being able to do what this does -so thanks a million.
I notice in the logs frequent GET requests:

webscrapbook_1 | 127.0.0.1 - - [31/Aug/2021 13:11:36] "GET / HTTP/1.1" 200 -
webscrapbook_1 | 127.0.0.1 - - [31/Aug/2021 13:11:41] "GET / HTTP/1.1" 200 -
webscrapbook_1 | 127.0.0.1 - - [31/Aug/2021 13:11:47] "GET / HTTP/1.1" 200 -
webscrapbook_1 | 127.0.0.1 - - [31/Aug/2021 13:11:52] "GET / HTTP/1.1" 200 -
webscrapbook_1 | 127.0.0.1 - - [31/Aug/2021 13:11:57] "GET / HTTP/1.1" 200 -
webscrapbook_1 | 127.0.0.1 - - [31/Aug/2021 13:12:03] "GET / HTTP/1.1" 200 -

Do you know if this is a docker process on localhost responsible for periodically connecting to the container?

Its behind traefik, but I disabled that and saw the same behaviour.

Any insight would be much appreciated.

Regards,

Geoff.

**Comment by gtothill** [comment]
Ah - I have just seen this in the Dockerfile:

HEALTHCHECK --interval=5s --timeout=3s --start-period=20s CMD /health_check.sh

Im assuming that this is what Im seeing. Can you explain what it is doing?

Cheers

Geoff.

**Comment by vsc55** [comment]
Hi @gtothill,

These records are normal and generated by HEALTHCHECK.
It is used to verify that the service is alive and responding correctly, since verifying that the process is started does not always indicate that the service is working correctly. Generating the query we check two things, 1 that the service is started, and 2 that the service is not blocked and answers the queries correctly. 

Cheers

**Comment by vsc55** [comment]
I have increased the times so that it does not check the status so continuously.

**Comment by gtothill** [comment]
Excellent - thanks for your explanation and for reducing the frequency of HEALTHCHECK.

**Comment by vsc55** [comment]
No problem, those low times seem to me that they remained unchanged after doing some test.🧪🧪
My fault, sorry. 😄
