### ISSUE TITLE
Arm 64v8 image

### ISSUE THREAD

**Issue by gtothill** [vsc55/docker-PyWebScrapBook#4]
Hi,
I have another quick question, which I should probably know the answer to.
I would really like to run the server in docker on a Raspberry Pi running the 64bit rasbian.
Would it be complex to produce an Arm 64v8 image for the server?
Is it just a matter of compiling the Dockerfile on a Pi ?
Any pointers would be most appreciated.
Cheers.

**Comment by vsc55** [comment]
Hi, 
The docker is based on python: 3.7.7-alpine and there is a version for ARM so in principle I think there will be no problem.
See if I can get some time and look at it.

**Comment by gtothill** [comment]
Excellent - thanks a million. I’m in the process of moving all the services that I previously ran on a monolithic Linux server into several small Raspberry Pi 4’s. So far Ive moved Plex, Paperless-Ng and XWiki and WebScrapBook seems to be perfect for this strategy. Cheers, Geoff.

**Comment by vsc55** [comment]
Hi @gtothill,
The last image (version 1.1.0) is also prepared for ARM64. 
If you want, you can try to see if it works correctly in Raspberry and comment on the results. 
Thank you and happy holidays.
